export const categories = [
  { label: 'Comestibles', value: 'COMESTIBLES' },
  { label: 'Limpieza', value: 'LIMPIEZA' },
  { label: 'Bebidas', value: 'BEBIDAS' },
  { label: 'Snacks', value: 'SNACKS' },
  { label: 'Congelados', value: 'CONGELADOS' },
  { label: 'Lácteos', value: 'LACTEOS' },
  { label: 'Panadería', value: 'PANADERIA' },
  { label: 'Carnes frías', value: 'CARNES_FRIAS' },
  { label: 'Frutas y verduras', value: 'FRUTAS_VERDURAS' },
  { label: 'Higiene personal', value: 'HIGIENE_PERSONAL' },
  { label: 'Hogar', value: 'HOGAR' },
  { label: 'Cuidado del bebé', value: 'CUIDADO_BEBE' },
  { label: 'Mascotas', value: 'MASCOTAS' },
  { label: 'Otros', value: 'OTROS' },
  { label: 'Canasta basica', value: 'CANASTA_BASICA' },
  { label: 'Seriales', value: 'SERIALES' },
]
